name: GitHub Actions Build dnsmasq-china-list-smartdns
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *" #北京时间每日零点启动
  push:
    branches:
      - master
#  watch:
#    types: [started]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install curl git wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/felixonmars/dnsmasq-china-list.git
        cd dnsmasq-china-list
        make raw
        mkdir -p /tmp/upload/
        cp ./accelerated-domains.china.raw.txt /tmp/upload/
        #合并
        cat ./google.china.raw.txt >> /tmp/upload/accelerated-domains.china.raw.txt 2>/dev/null
        cat ./apple.china.raw.txt >> /tmp/upload/accelerated-domains.china.raw.txt 2>/dev/null
        #压缩（直接txt，Gitee会触发违禁词异常）
        tar -zcvf /tmp/upload/accelerated-domains.china.raw.txt.tar.gz -C /tmp/upload/ accelerated-domains.china.raw.txt
        
    - name: Set variables
      run: |
        echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        
#    - name: Release and upload assets
#      uses: softprops/action-gh-release@v0.1.6
#      with:
#        name: ${{ env.RELEASE_NAME }}
#        tag_name: ${{ env.TAG_NAME }}
#        draft: false
#        prerelease: false
#        files: |
#            /tmp/upload/accelerated-domains.china.raw.txt.tar.gz
#      env:
#        GITHUB_TOKEN: ${{ secrets.MYTOKEN }}  
       
    - name: Git push assets to "release" branch
      run: |
         cd /tmp/upload/ || exit 1
         git init
         git config --local user.name "github-actions[bot]"
         git config --local user.email "github-actions[bot]@users.noreply.github.com"
         git checkout -b release
         git add .
         git commit -m "${{ env.RELEASE_NAME }}"
         git remote add origin "https://${{ github.actor }}:${{ secrets.MYTOKEN }}@github.com/${{ github.repository }}"
         git push -f -u origin release
      
    - name: Purge jsdelivr CDN
      run: |
        cd /tmp/upload/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
        done

    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:quou2006/auto-dnsmasq-china-list.git"
        # 目标仓库
        destination-repo: "git@gitee.com:quou2006/auto-dnsmasq-china-list.git"

